[package]
name = "kcacheext"
version = "0.3.1"
authors = ["Marco Grassi <marco.gra@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.2.20"
bytesize = "1.0.0"
packed_struct = "0.10.0"
packed_struct_codegen = "0.10.0"
byteorder = "1.3.1"
lzfse = "0.1.0"
